# Generated by Django 3.1.5 on 2021-01-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210115_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_types',
        ),
    ]
