# Generated by Django 3.1.5 on 2021-01-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210116_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ManyToManyField(null=True, to='accounts.UserType', verbose_name='User Type'),
        ),
    ]
