# Generated by Django 3.1.5 on 2021-01-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210120_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.ManyToManyField(to='accounts.UserType', verbose_name='User Type'),
        ),
    ]
