# Generated by Django 3.1.5 on 2021-02-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210129_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Create Room',
                'verbose_name_plural': 'Create Rooms',
            },
        ),
        migrations.CreateModel(
            name='GetRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_link', models.URLField(blank=True, null=True)),
                ('room_name', models.CharField(blank=True, max_length=80)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
