# Generated by Django 3.1.5 on 2021-02-02 15:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_createroom_getrooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateIvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Create Room',
                'verbose_name_plural': 'Create Rooms',
            },
        ),
        migrations.DeleteModel(
            name='CreateRoom',
        ),
    ]
